//go:build ignore

// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache-2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth_inline": {
            "get": {
                "description": "Header-driven decision endpoint for Nginx auth_request integrations. Returns status/header outcomes only (no JSON response body on any status). Required headers: X-Real-IP and X-URL. Optional headers: X-UA and X-Request-ID. Optional Cookie header carries the auth cookie and any issued cookie uses Secure=true, HttpOnly=true, SameSite=Lax.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Inline authorization decision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client IP address",
                        "name": "X-Real-IP",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Original requested URL",
                        "name": "X-URL",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client user agent",
                        "name": "X-UA",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Request correlation identifier",
                        "name": "X-Request-ID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Auth cookie for token validation",
                        "name": "Cookie",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Allowed"
                    },
                    "302": {
                        "description": "Redirect (Location header)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Challenge required — responds with X-Auth-Action: challenge header only, no body"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "444": {
                        "description": "Connection dropped (Nginx-specific)"
                    },
                    "503": {
                        "description": "Service unavailable"
                    }
                }
            }
        },
        "/api/challenge": {
            "get": {
                "description": "Returns PoW challenge parameters for a protected target. Requires X-Real-IP header; X-URL header is preferred, and if absent, the pow_target cookie is used as fallback. X-UA is optional.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Issue proof-of-work challenge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client IP address",
                        "name": "X-Real-IP",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Original requested URL (falls back to pow_target cookie if absent)",
                        "name": "X-URL",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Client user agent",
                        "name": "X-UA",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ChallengeResponse"
                        }
                    },
                    "400": {
                        "description": "Plain text error: 'invalid client ip' or 'missing X-URL header'",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/verify_pow": {
            "post": {
                "description": "Validates submitted PoW, prevents nonce replay, then redirects with an auth cookie. Requires X-Real-IP header; X-UA is optional. Accepts JSON body (modeled in OpenAPI spec). The runtime also accepts application/x-www-form-urlencoded form submissions with the same field names, but this is not modeled in the spec for Swagger 2.0 compatibility.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify proof-of-work submission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client IP address",
                        "name": "X-Real-IP",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client user agent",
                        "name": "X-UA",
                        "in": "header"
                    },
                    {
                        "description": "PoW submission",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apidoc.VerifyPoWRequest"
                        }
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to target with cookie (Set-Cookie and Location headers)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "JSON-shaped error body via http.Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.VerifyPoWError"
                        }
                    },
                    "403": {
                        "description": "JSON-shaped error body via http.Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.VerifyPoWError"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service unavailable — may be JSON-shaped error or plain text",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apidoc.ChallengeResponse": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "description": "Difficulty is the required number of leading zero bits/characters for PoW validation.",
                    "type": "integer",
                    "example": 5
                },
                "prefix": {
                    "description": "Prefix is the signed challenge prefix tied to client subnet and target.",
                    "type": "string",
                    "example": "1700000000:abcdef12:signaturehex"
                },
                "target": {
                    "description": "Target is the protected resource URL that this challenge authorizes when solved.",
                    "type": "string",
                    "example": "https://mirror.example.com/file.iso"
                }
            }
        },
        "apidoc.VerifyPoWError": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a machine-readable error code for programmatic handling.",
                    "type": "string",
                    "example": "invalid proof of work"
                }
            }
        },
        "apidoc.VerifyPoWRequest": {
            "type": "object",
            "properties": {
                "nonce": {
                    "description": "Nonce is the client-computed value that satisfies the requested PoW difficulty.",
                    "type": "string",
                    "example": "42"
                },
                "prefix": {
                    "description": "Prefix is the signed challenge prefix returned by the challenge endpoint.",
                    "type": "string",
                    "example": "1700000000:abcdef12:signaturehex"
                },
                "target_uri": {
                    "description": "TargetURI is the original protected URL to redirect to after successful verification.",
                    "type": "string",
                    "example": "https://mirror.example.com/file.iso"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Mirror Guard Auth Gateway API",
	Description:      "Authentication gateway endpoints for inline authorization, challenge issuance, and PoW verification.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
